//
// // REDUCER EVENTS
//
export const CONTACT_ME_FIELD_UPDATE = "CONTACT_ME_FIELD_UPDATE"

//
// // SAGA EVENTS
//
export const CONTACT_ME_FIELD_CHANGED = 'CONTACT_ME_FIELD_CHANGED'
export const CONTACT_ME_FIELD_SUBMITTED = "CONTACT_ME_FIELD_SUBMITTED"