//
// // REDUCER EVENTS
//

// Contact Me Reducer
export const CONTACT_ME_FIELD_UPDATE = "CONTACT_ME_FIELD_UPDATE"
export const CONTACT_ME_RESET_FIELDS = "CONTACT_ME_RESET_FIELDS"

// META Reducer
export const FETCH_REQUEST_STARTED = "FETCH_REQUEST_STARTED"
export const FETCH_REQUEST_FINISHED = "FETCH_REQUEST_FINISHED"
export const INFINITE_REQUEST_STARTED = "INFINITE_REQUEST_STARTED"
export const INFINITE_REQUEST_FINISHED = "INFINITE_REQUEST_FINISHED"

//
// // SAGA EVENTS
//

// Contact Me
export const CONTACT_ME_FIELD_CHANGED = "CONTACT_ME_FIELD_CHANGED"
export const CONTACT_ME_FIELD_SUBMITTED = "CONTACT_ME_FIELD_SUBMITTED"

// Toasts
export const NEW_TOAST = "NEW_TOAST"
export const DELETE_TOAST = "DELETE_TOAST"
export const CREATE_TOAST_MESSAGE = "CREATE_TOAST_MESSAGE"
export const REMOVE_TOAST_MESSAGE = "REMOVE_TOAST_MESSAGE"